const menu = [
  {
    id: "1",
    title: "Ciorba de legume",
    category: "Ciorbe şi supe",
    price: 20,
    img: "./images/ciorba-de-legume.jpg",
    desc: `Apă – 280g, Cartofi – 30g, Țelină – 10g, Ceapă – 10g, Ardei dulce – 10g, Morcov – 10g, Pasta de tomate – 10g, Roșii decojite (conservă) – 10g, Bors – 10g, (Apa, tarate de GRAU. Produs obtinut din fermentarea taratei de grau. Datorita procesului natural de fermentare produsul poate prezenta sedimente.), Piper negru – 5g, Pătrunjel – 5g, Ulei de floarea soarelui – 5g, Sare – 5g `,
  },

  {
    id: "2",
    title: "Ciorba de vacuta",
    category: "Ciorbe şi supe",
    price: 20,
    img: "./images/Ciorba-de-Vacuta.jpg",
    desc: "Apă – 170g, Carne de vită – 100g, Cartofi – 30g, Țelină – 10g, Ceapă – 10g, Ardei dulce – 10g, Morcov – 10g, Pasta de tomate – 10g, Roșii decojite (conservă) – 10g, Bors – 10g, (Apa, tarate de GRAU. Produs obtinut din fermentarea taratei de grau. Datorita procesului natural de fermentare produsul poate prezenta sedimente.), Fasole verde pastai* – 10g, (Fasole verde 100%.), Piper negru – 5g, Pătrunjel – 5g, Ulei de floarea soarelui – 5g, Sare – 5g ",
  },

  {
    id: "3",
    title: "Ciorbă de perişoare",
    category: "Ciorbe şi supe",
    price: 20,
    img: "./images/Ciorba-de-perisoare.jpg",
    desc: "Apă – 170g, Perișoare – 140g (Piept de pui – 90g, Piper negru – 5g, Orez – 40g, Sare – 5g), Țelină – 10g, Ceapă – 10g, Ardei dulce – 10g, Morcov – 10g, Pasta de tomate – 10g, Roșii decojite (conservă) – 10g, Bors – 10g, (Apa, tarate de GRAU. Produs obtinut din fermentarea taratei de grau. Datorita procesului natural de fermentare produsul poate prezenta sedimente.), Piper negru – 5g, Pătrunjel – 5g, Ulei de floarea soarelui – 5g, Sare – 5g",
  },
  {
    id: "4",
    title: "Ciorbă rădăuțeană",
    category: "Ciorbe şi supe",
    price: 21,
    img: "./images/ciorba-radauteana.jpg",
    desc: "Apă – 195g, Piept de pui – 100g, Smântână – 20g, Țelină – 10g, Cartofi – 10g, Ceapă – 10g, Ou – 10g, Ardei dulce – 10g, Morcov – 10g, Usturoi – 5g, Piper negru – 5g, Pătrunjel – 5g, Sare – 5g, Otet de mere / Otet de vin – 5g, Ulei de floarea soarelui – 5g",
  },
  {
    id: "5",
    title: "Supă de pui",
    category: "Ciorbe şi supe",
    price: 18,
    img: "./images/supa-pui.jpg",
    desc: "Zeamă de pui – 230g (Pulpe de pui – 100g, Apă – 130g), Găluște – 120g (Griș – 70g, Ou – 45g, Sare – 5g), Morcov – 20g, Ceapă – 10g, Piper negru – 5g, Pătrunjel – 5g, Ulei de floarea soarelui – 5g, Sare – 5g",
  },
  {
    id: "6",
    title: "Ciorbe şi supe",
    category: "Ciorbe şi supe",
    price: 20,
    img: "./images/ciorba-de-fasole.jpg",
    desc: "Apă – 270g, Fasole – 35g, Țelină – 10g, Ceapă – 10g, Ardei dulce – 10g, Morcov – 10g, Pasta de tomate – 10g, Roșii decojite (conservă) – 10g, Bors – 10g, (Apa, tarate de GRAU. Produs obtinut din fermentarea taratei de grau. Datorita procesului natural de fermentare produsul poate prezenta sedimente.), Piper negru – 5g, Pătrunjel – 5g, Ulei de floarea soarelui – 5g, Sare – 5g, Cimbru – 5g",
  },

  {
    id: "7",
    title: "Chiftele de pui",
    category: "Preparate din carne",
    price: 23,
    img: "./images/chiftele-pui.jpg",
    desc: "Pulpe de pui – 34g, Piept de pui – 33g, Ou – 10g, Usturoi – 5g, Ceapă – 5g, Morcov – 5g, Piper negru – 2g, Pătrunjel – 2g, Sare – 2g, Mărar – 2g",
  },
  {
    id: "8",
    title: "Pulpă de pui",
    category: "Preparate din carne",
    price: 14,
    img: "./images/pulpa-de-pui.jpg",
    desc: "ulpe de pui – 100g, Bere 4 – 5g, Muştar – 2g, Usturoi – 1g, Piper negru – 1g, Ulei de floarea soarelui – 1g, Sare – 1g, boia dulce – 1g",
  },
  {
    id: "9",
    title: "Șnițel din piept",
    category: "Preparate din carne",
    price: 14,
    img: "./images/snitel-de-pui.jpg",
    desc: "Piept de pui – 100g, Bechamel – 50g (Usturoi – 2g, Ou – 100g, Piper negru – 2g, făină de grâu – 50g, Muştar – 5g, Sare – 2g, Pesmet – 20g)",
  },
  {
    id: "10",
    title: "Piept de pui la grătar",
    category: "Preparate din carne",
    price: 15,
    img: "./images/piept-de-pui-la-gratar.jpg",
    desc: "Piept de pui – 95g, Usturoi – 1g, Piper negru – 1g, Ulei de floarea soarelui – 1g, Sare – 1g, boia dulce – 1g",
  },
  {
    id: "11",
    title: "Ficăței de pui",
    category: "Preparate din carne",
    price: 15,
    img: "./images/ficatei-de-pui.jpg",
    desc: "Apă – 195g, Piept de pui – 100g, Smântână – 20g, Țelină – 10g, Cartofi – 10g, Ceapă – 10g, Ou – 10g, Ardei dulce – 10g, Morcov – 10g, Usturoi – 5g, Piper negru – 5g, Pătrunjel – 5g, Sare – 5g, Otet de mere / Otet de vin – 5g, Ulei de floarea soarelui – 5g",
  },
  {
    id: "12",
    title: "Cordon bleu de porc",
    category: "Preparate din carne",
    price: 15,
    img: "./images/cordon-bleu-de-porc.jpg",
    desc: "2 felii de pulpa de porc (pentru snitele),6- felii subtiri de sunca presata,50 g -cascaval, sare piper,  2- oua,  faina,  pesmet,  ulei pentru praji,",
  },
  {
    id: "13",
    title: "Cârnați de porc",
    category: "Preparate din carne",
    price: 12,
    img: "./images/carnati-de-porc.jpg",
    desc: "Carne tocată de porc – 80g, Slănină de porc – 50g, Carne tocată de vită – 50g, Usturoi – 5g, boia dulce – 5g, Sare – 3g, Piper negru – 2g, Stabilizator: Nitrit de sodiu (E 250)",
  },

  {
    id: "14",
    title: "Sarmale cu smantână şi mămăligă",
    category: "Preparate din carne",
    price: 24,
    img: "./images/sarmale.jpg",
    desc: "Mămăligă – 150g (Ulei de floarea soarelui – 2g, Sare – 2g, Apă – 196g, Faina de malai – 50g), Carne tocată de porc – 136g, Varză murată – 50g, Orez – 30g, Pasta de tomate – 10g, Ceapă – 5g, Pătrunjel – 5g, Morcov – 5g, Piper negru – 3g, Sare – 3g, Cimbru – 3g",
  },
  {
    id: "15",
    title: "Ceafă de porc la grătar",
    category: "Preparate din carne",
    price: 16,
    img: "./images/ceafa-de-porc-la-gratar.jpg",
    desc: "Ceafa de porc – 100g, Vin alb – 10g, Usturoi – 4g, Piper negru – 2g, Sare – 2g, boia dulce – 2g",
  },

  {
    id: "16",
    title: "Ciolan afumat la cuptor",
    category: "Preparate din carne",
    price: 16,
    img: "./images/ciolan-la-cuptor.jpeg",
    desc: "1 ciolan crud si afumat de cca. 1 kg (cu tot cu os),1 ceapa rosie,1 ceapa alba,boabe de piper, boabe de ienupar,chimen, sare",
  },
  {
    id: "17",
    title: "Orez cu legume",
    price: 18,
    category: "Garnituri",
    img: "./images/orez-cu-legume.jpg",
    desc: "Apă – 91g, Orez – 50g, legume – 50g (Ceapă – 10g, Ardei dulce – 15g, Morcov – 15g, Spanac – 10g), Ulei de floarea soarelui – 5g, Piper negru – 2g, Sare – 2g",
  },
  {
    id: "18",
    title: "Mazăre",
    category: "Garnituri",
    price: 21,
    img: "./images/mazare.jpg ",
    desc: "Apă – 92g, Mazăre – 50g, Țelină – 10g, Ceapă – 10g, Morcov – 10g, Pasta de tomate – 10g, Roșii decojite (conservă) – 10g, Piper negru – 2g, Sare – 2g, Mărar – 2g, Frunza de dafin – 1g, Cimbru – 1g",
  },
  {
    id: "19",
    title: "Piure de cartofi",
    category: "Garnituri",
    price: 12,
    img: "./images/piure-de-cartofi.jpg",
    desc: "Cartofi – 138g, Lapte – 30g, Unt – 30g, Sare – 2g",
  },
  {
    id: "20",
    title: "Cartofi la cuptor",
    price: 10,
    category: "Garnituri",
    img: "./images/cartofi-la-cuptor.jpg",
    desc: "Cartofi – 140g, Ulei de floarea soarelui – 7g, Sare – 3g",
  },

  {
    id: "21",
    title: "Iahnie de fasole",
    price: 17,
    category: "Garnituri",
    img: "./images/Iahnie de fasole.jpeg",
    desc: "Apă – 92g, Fasole – 50g, Țelină – 10g, Ceapă – 10g, Morcov – 10g, Pasta de tomate – 10g, Roșii decojite (conservă) – 10g, Piper negru – 2g, Sare – 2g, Mărar – 2g, Frunza de dafin – 1g, Cimbru – 1g",
  },

  {
    id: "22",
    title: "Castraveți murați",
    category: "Salate",
    price: 8,
    img: "./images/Castraveti-murati.jpg",
    desc: "Castraveti murati – 150g, (Castraveti cornichon 55%, apa, otet, zahar, sare, ceapa, piper, boabe de MUSTAR, marar, arome.)",
  },
  {
    id: "23",
    title: "Salată de varză",
    category: "Salate",
    price: 8,
    img: "./images/salata-varza.jpg",
    desc: "Varză albă – 145g, Ulei de floarea soarelui – 3g, Sare – 2g",
  },
  {
    id: "24",
    title: "Varză murată",
    category: "Salate",
    price: 8,
    img: "./images/Varza-murata.jpg",
    desc: "Varză murată – 145g, Ulei de floarea soarelui – 3g, Piper negru – 2g",
  },

  {
    id: "25",
    title: "Salată de sfeclă roșie cu hrean",
    category: "Salate",
    price: 10,
    img: "./images/Salata-de-sfecla-rosie.jpg",
    desc: "Sfeclă roșie – 107g, Hrean în oțet iute – 30g, Ulei de floarea soarelui – 5g, Sare -3g, Oțet de vin – 3g, Zahăr – 2g",
  },

  
];
export default menu;
